
spring.application.name=graphql-product-api
# Server
server.port=8080

# SQL Server connection
spring.datasource.url=jdbc:sqlserver://localhost\\DUYSQL:1433;databaseName=bai09;encrypt=false;trustServerCertificate=true
spring.datasource.username=sa
spring.datasource.password=40938813dD#
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.open-in-view=false

